version = 0.1
[default.deploy.parameters]
stack_name = "style-mini-app-__ENV__"
resolve_s3 = true
s3_prefix = "style-mini-app-__ENV__"
region = "eu-west-3"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
